version: "3.3"
services:
  db:
    image: mongo:5.0.5
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ./mongo-env.env
volumes:
  mongodata:
    external: true
