version: "3.3"
services:
  db:
    image: postgres:9.6.24-alpine3.15
    ports:
      - "5432:5432"
    env_file:
      - ./postgres-env.env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    external: true
